---
title: "homicides"
author: "Mariana Meza Hernandez"
date: "January 17, 2019"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(forcats)
```

```{r}
homicide <- read_csv("homicide_snsp_month.csv")
```
```{r}
homicide_long <- gather (homicide, month, homicides, January:December, factor_key = TRUE) 
```

This code produces a data frame with the total homicides per month by year
```{r}
month_year <- 
  homicide_long %>%
  group_by(year, month) %>%
  summarize(total_homicides = sum(homicides))
```

```{r}
ggplot(data = month_year) +
  geom_tile(aes(x = month, y =year, fill = total_homicides))
```
Total homicides by month and year with a fire arm 

```{r}
month_year_gun <-
  homicide_long %>%
  filter(subtype == "CON ARMA DE FUEGO") %>%
  filter (year > "2000") %>%
  group_by(year, month) %>%
  summarize(total_gun = sum(homicides))
```

```{r}
ggplot(data = month_year_gun) +
  geom_tile(aes(x = month, y =year, fill = total_gun)) +
  scale_y_continuous(breaks = 1997:2017) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_hline(aes(yintercept=2006), color="white") +
  #guides(fill=guide_legend("Homicides by firearm")) +
  ggtitle("Total homicides by firearm by month in Mexico") +
  labs(x = "Month", y = "Year", fill= "Homicides by firearm", caption = "Source: SNSP: Homicide records by the police")  +
   annotate("text", x = "May", y = 2005, label = "War Against Organized Crime Begins", size = 3.5, color = "white") 
```

With gun and knife

```{r}
month_year_weapon <-
  homicide_long %>%
  filter(subtype == "CON ARMA DE FUEGO" | subtype == "CON ARMA BLANCA") %>%
  group_by(year, month) %>%
  summarize(total_weapon = sum(homicides))
```

```{r}
ggplot(data = month_year_weapon) +
  geom_tile(aes(x = month, y =year, fill = total_weapon))
```


INEGI death certificate data for 2017

```{r}
death_2017 <- read_csv("d.csv")
```
```{r}
# lista_mex == 55 son los casos de homicidio 
  death_2017_homicide <- filter (death_2017, lista_mex == "55")
  death_2017_homicide <- filter (death_2017_homicide, sexo == "1" | sexo =="2")
  death_2017_homicide <- filter (death_2017_homicide, edad > 3098)

  

```



```{r}
death_2017_homicide <-
  death_2017_homicide %>%
  mutate (
    cause = str_sub(death_2017_homicide$causa_def, 1,3),
    age = str_sub(death_2017_homicide$edad, 3,4),
    year = death_2017_homicide$anio_regis
  )
```

Creating factor levels for cause of homicide
```{r}
death_2017_homicide %>%
count(cause)
```
```{r}
ggplot(data = death_2017_homicide) +
geom_bar(mapping = aes(x = cause, y = ..prop.., group = sexo, fill = factor(sexo)),stat = "count", position = "dodge")+ coord_flip()
```

```{r}
factor(death_2017_homicide$cause)
```

```{r}
ggplot(data = death_2017_homicide) +
geom_bar(mapping = aes(x = cause, y = ..prop.., group = sexo, fill = factor(sexo)),stat = "count", position = "dodge")+ coord_flip()
```
```{r}
death_2017_homicide <-
  death_2017_homicide %>%
  mutate(
    sexo2 = ifelse(sexo ==1, "Men", "Women") 
  )
```



```{r}
death_2017_homicide <-
death_2017_homicide %>%
  mutate(cause2 = fct_recode(cause,
    "Y09"    = "Other non-specified means",
    "X99"      = "Knife",
    "X95" = "Non-specified firearm",
    "X91" = "Asphyxiation",
    "X93"        = "Short firearm",
    "Other"      = "X85",
    "Other"                 = "X86",
    "Other"                 = "X87",
    "Other"                 = "X88",
    "Other"                 = "X89",
    "Other"                 = "X90",
    "Other"                 = "X92",
    "Other"                 = "X94",
    "Other"                 = "X96",
    "Other"                 = "X97",
    "Other"                 = "X98",
    "Other"                 = "Y00",
    "Other"                 = "Y01",
    "Other"                 = "Y02",
    "Other"                 = "Y03",
    "Other"                 = "Y04",
    "Other"                 = "Y05",
    "Other"                 = "Y06",
    "Other"                 = "Y07",
    "Other"                 = "Y08"
  )) 
levels(death_2017_homicide$cause2)[levels(death_2017_homicide$cause2)=="X91"] <- "Asphyxiation"
levels(death_2017_homicide$cause2)[levels(death_2017_homicide$cause2)=="X93"] <- "Short firearm"
levels(death_2017_homicide$cause2)[levels(death_2017_homicide$cause2)=="Y09"] <- "Other unspecified means"
levels(death_2017_homicide$cause2)[levels(death_2017_homicide$cause2)=="X99"] <- "Knife"
levels(death_2017_homicide$cause2)[levels(death_2017_homicide$cause2)=="X95"] <- "Unspecified firearm"




levels(death_2017_homicide$cause2)
ggplot(death_2017_homicide) +
geom_bar(mapping = aes(x = cause2, y = ..prop.., group = sexo2, fill = factor(sexo2)),stat = "count", position = "dodge")+ coord_flip()+
  guides(fill=guide_legend("Homicides by firearm")) 
  
```

```{r}
levels(death_2017_homicide$cause2)
ggplot(death_2017_homicide) +
geom_bar(mapping = aes(x = cause2, y = ..prop.., group = sexo2, fill = factor(sexo2)),stat = "count", position = "dodge")+ coord_flip()+
  scale_fill_manual ("Gender", values = c("Men" = " navy blue", "Women" = "666")) +
  labs(x = "Cause of homicide", y = "Proportion", subtitle = "Proportion of cause of homicide by gender (2000-2017)", caption = "Source: INEGI: Mortality Statistics") +
  ggtitle("How are men and women killed?") +
  
  guides(fill=guide_legend("Gender")) 
```

```{r}
incidencia <- (read_csv("denunciados_incidencia.csv"))
```

```{r}
  ggplot (incidencia) +
  geom_point(mapping = aes(x = corrupcion_mp, y = delitos_denunciados, size = delitos_ocurridos, label = State)) +
  geom_text(mapping= aes(label=State),hjust=0,vjust=0)
  
```
```{r}
ggplot(incidencia, aes(x= corrupcion_mp, y = delitos_denunciados,size = delitos_ocurridos, label = State, alpha = 0.4)) +
  
  geom_point() +
  geom_text(aes(label=ifelse(delitos_denunciados>100000,as.character(State),'')),hjust=1.1,vjust=1)+
  geom_smooth()
  
  #geom_text(aes(label=State),hjust=0, vjust=0)
```
```{r}
ggplot(incidencia, aes(x= corrupcion_mp, y = delitos_denunciados,size = delitos_ocurridos, label = State)) +
  geom_point(color = ifelse(incidencia$delitos_denunciados > 120005 & incidencia$corrupcion_mp < 80, "red", "blue")) +
  labs(x = "Percent who say state attorneys are corrupt", y = "Reported crimes", subtitle = "by state and rate of crimes per 100,000", caption = "Source: ENVIPE: Public Security and Trust Survey", size = "Number of crimes per 100,000") +
  ggtitle("Perception of corruptio and number of reported crimes") +
  geom_text(aes(label=ifelse(delitos_denunciados>120005,as.character(State),'')),hjust=1.1,vjust=0)+
  geom_smooth()
```

